/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateClassificationResponseSelectedExamplesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateClassificationResponseSelectedExamplesInner{}

// CreateClassificationResponseSelectedExamplesInner struct for CreateClassificationResponseSelectedExamplesInner
type CreateClassificationResponseSelectedExamplesInner struct {
	Document *int32 `json:"document,omitempty"`
	Text *string `json:"text,omitempty"`
	Label *string `json:"label,omitempty"`
}

// NewCreateClassificationResponseSelectedExamplesInner instantiates a new CreateClassificationResponseSelectedExamplesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateClassificationResponseSelectedExamplesInner() *CreateClassificationResponseSelectedExamplesInner {
	this := CreateClassificationResponseSelectedExamplesInner{}
	return &this
}

// NewCreateClassificationResponseSelectedExamplesInnerWithDefaults instantiates a new CreateClassificationResponseSelectedExamplesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateClassificationResponseSelectedExamplesInnerWithDefaults() *CreateClassificationResponseSelectedExamplesInner {
	this := CreateClassificationResponseSelectedExamplesInner{}
	return &this
}

// GetDocument returns the Document field value if set, zero value otherwise.
func (o *CreateClassificationResponseSelectedExamplesInner) GetDocument() int32 {
	if o == nil || IsNil(o.Document) {
		var ret int32
		return ret
	}
	return *o.Document
}

// GetDocumentOk returns a tuple with the Document field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponseSelectedExamplesInner) GetDocumentOk() (*int32, bool) {
	if o == nil || IsNil(o.Document) {
		return nil, false
	}
	return o.Document, true
}

// HasDocument returns a boolean if a field has been set.
func (o *CreateClassificationResponseSelectedExamplesInner) HasDocument() bool {
	if o != nil && !IsNil(o.Document) {
		return true
	}

	return false
}

// SetDocument gets a reference to the given int32 and assigns it to the Document field.
func (o *CreateClassificationResponseSelectedExamplesInner) SetDocument(v int32) {
	o.Document = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *CreateClassificationResponseSelectedExamplesInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponseSelectedExamplesInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *CreateClassificationResponseSelectedExamplesInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *CreateClassificationResponseSelectedExamplesInner) SetText(v string) {
	o.Text = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CreateClassificationResponseSelectedExamplesInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateClassificationResponseSelectedExamplesInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CreateClassificationResponseSelectedExamplesInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CreateClassificationResponseSelectedExamplesInner) SetLabel(v string) {
	o.Label = &v
}

func (o CreateClassificationResponseSelectedExamplesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateClassificationResponseSelectedExamplesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Document) {
		toSerialize["document"] = o.Document
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	return toSerialize, nil
}

type NullableCreateClassificationResponseSelectedExamplesInner struct {
	value *CreateClassificationResponseSelectedExamplesInner
	isSet bool
}

func (v NullableCreateClassificationResponseSelectedExamplesInner) Get() *CreateClassificationResponseSelectedExamplesInner {
	return v.value
}

func (v *NullableCreateClassificationResponseSelectedExamplesInner) Set(val *CreateClassificationResponseSelectedExamplesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateClassificationResponseSelectedExamplesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateClassificationResponseSelectedExamplesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateClassificationResponseSelectedExamplesInner(val *CreateClassificationResponseSelectedExamplesInner) *NullableCreateClassificationResponseSelectedExamplesInner {
	return &NullableCreateClassificationResponseSelectedExamplesInner{value: val, isSet: true}
}

func (v NullableCreateClassificationResponseSelectedExamplesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateClassificationResponseSelectedExamplesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


