/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateTranscriptionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTranscriptionResponse{}

// CreateTranscriptionResponse struct for CreateTranscriptionResponse
type CreateTranscriptionResponse struct {
	Text string `json:"text"`
}

// NewCreateTranscriptionResponse instantiates a new CreateTranscriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTranscriptionResponse(text string) *CreateTranscriptionResponse {
	this := CreateTranscriptionResponse{}
	this.Text = text
	return &this
}

// NewCreateTranscriptionResponseWithDefaults instantiates a new CreateTranscriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTranscriptionResponseWithDefaults() *CreateTranscriptionResponse {
	this := CreateTranscriptionResponse{}
	return &this
}

// GetText returns the Text field value
func (o *CreateTranscriptionResponse) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CreateTranscriptionResponse) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CreateTranscriptionResponse) SetText(v string) {
	o.Text = v
}

func (o CreateTranscriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTranscriptionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

type NullableCreateTranscriptionResponse struct {
	value *CreateTranscriptionResponse
	isSet bool
}

func (v NullableCreateTranscriptionResponse) Get() *CreateTranscriptionResponse {
	return v.value
}

func (v *NullableCreateTranscriptionResponse) Set(val *CreateTranscriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTranscriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTranscriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTranscriptionResponse(val *CreateTranscriptionResponse) *NullableCreateTranscriptionResponse {
	return &NullableCreateTranscriptionResponse{value: val, isSet: true}
}

func (v NullableCreateTranscriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTranscriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


