/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateTranslationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTranslationResponse{}

// CreateTranslationResponse struct for CreateTranslationResponse
type CreateTranslationResponse struct {
	Text string `json:"text"`
}

// NewCreateTranslationResponse instantiates a new CreateTranslationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTranslationResponse(text string) *CreateTranslationResponse {
	this := CreateTranslationResponse{}
	this.Text = text
	return &this
}

// NewCreateTranslationResponseWithDefaults instantiates a new CreateTranslationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTranslationResponseWithDefaults() *CreateTranslationResponse {
	this := CreateTranslationResponse{}
	return &this
}

// GetText returns the Text field value
func (o *CreateTranslationResponse) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *CreateTranslationResponse) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *CreateTranslationResponse) SetText(v string) {
	o.Text = v
}

func (o CreateTranslationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTranslationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

type NullableCreateTranslationResponse struct {
	value *CreateTranslationResponse
	isSet bool
}

func (v NullableCreateTranslationResponse) Get() *CreateTranslationResponse {
	return v.value
}

func (v *NullableCreateTranslationResponse) Set(val *CreateTranslationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTranslationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTranslationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTranslationResponse(val *CreateTranslationResponse) *NullableCreateTranslationResponse {
	return &NullableCreateTranslationResponse{value: val, isSet: true}
}

func (v NullableCreateTranslationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTranslationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


