/*
OpenAI API

APIs for sampling from and fine-tuning language models

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ChatCompletionResponseMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionResponseMessage{}

// ChatCompletionResponseMessage struct for ChatCompletionResponseMessage
type ChatCompletionResponseMessage struct {
	// The role of the author of this message.
	Role string `json:"role"`
	// The contents of the message
	Content string `json:"content"`
}

// NewChatCompletionResponseMessage instantiates a new ChatCompletionResponseMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionResponseMessage(role string, content string) *ChatCompletionResponseMessage {
	this := ChatCompletionResponseMessage{}
	this.Role = role
	this.Content = content
	return &this
}

// NewChatCompletionResponseMessageWithDefaults instantiates a new ChatCompletionResponseMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionResponseMessageWithDefaults() *ChatCompletionResponseMessage {
	this := ChatCompletionResponseMessage{}
	return &this
}

// GetRole returns the Role field value
func (o *ChatCompletionResponseMessage) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseMessage) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ChatCompletionResponseMessage) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value
func (o *ChatCompletionResponseMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionResponseMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ChatCompletionResponseMessage) SetContent(v string) {
	o.Content = v
}

func (o ChatCompletionResponseMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionResponseMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

type NullableChatCompletionResponseMessage struct {
	value *ChatCompletionResponseMessage
	isSet bool
}

func (v NullableChatCompletionResponseMessage) Get() *ChatCompletionResponseMessage {
	return v.value
}

func (v *NullableChatCompletionResponseMessage) Set(val *ChatCompletionResponseMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionResponseMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionResponseMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionResponseMessage(val *ChatCompletionResponseMessage) *NullableChatCompletionResponseMessage {
	return &NullableChatCompletionResponseMessage{value: val, isSet: true}
}

func (v NullableChatCompletionResponseMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionResponseMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


